### ISSUE TITLE
Menu Arrow

### ISSUE THREAD

**Issue by Eun** [swillits/NSMenu-Dark#1]
Is it possible to show the Arrow like the dock does?

![bildschirmfoto 2014-09-18 um 13 03 31](https://cloud.githubusercontent.com/assets/796084/4318833/a7f64c54-3f23-11e4-8220-4bfac04430a0.png)

**Comment by swillits** [comment]
Somehow possibly, but not with this code. That's specific to the Dock itself too - you never see it anywhere else.
